### ISSUE TITLE
What is the licence for this theme?

### ISSUE THREAD

**Issue by Talark-Systems** [lilbud/es-theme-switch#4]
I would like to make my own theme based on this one, however, I am unable to find the licence for this theme.

**Comment by lilbud** [comment]
Don't think there is one. A lot of themes have a "creative commons" license, though I think that's just a copy paste into the readme file. 

Make your own version, fine by me. Just credit me with original idea

**Comment by Dark3clipse** [comment]
@lilbud Am I allowed to incorporate this theme into emulationstation desktop edition? I really like the modern look of it and I think it will be a great enhancement to our project. I'll need to implement a number of improvements of features only available at es-de such that this theme also utilizes them. Of course, it is possible to credit you for the theme.

**Comment by lilbud** [comment]
Sure, go ahead, I got no problem as long as you credit me.
