### ISSUE TITLE
Retropie menu issue

### ISSUE THREAD

**Issue by ItsRedly** [lilbud/es-theme-switch#7]
Hi.

The retropie menu is completly messed up.

It says the game info text in the retropie menu.

Can you try to fix it.

Thanks.

DoorsDev

**Comment by lilbud** [comment]
I haven't touched anything retropie related in quite a while, so I wouldn't know where to begin, sorry.

You could probably try asking on the forums.

**Comment by ItsRedly** [comment]
Thanks for responding!
